CREATE TABLE IF NOT EXISTS design_task_comments (id INT AUTO_INCREMENT PRIMARY KEY, attachment_id INT NOT NULL, user_id INT NOT NULL, x_pos FLOAT NOT NULL, y_pos FLOAT NOT NULL, comment TEXT NOT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (attachment_id) REFERENCES design_task_attachments(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS design_task_tags (id INT AUTO_INCREMENT PRIMARY KEY, design_task_id INT NOT NULL, name VARCHAR(50) NOT NULL, color VARCHAR(20) NOT NULL, FOREIGN KEY (design_task_id) REFERENCES design_tasks(id) ON DELETE CASCADE);
ALTER TABLE design_tasks ADD COLUMN IF NOT EXISTS external_links TEXT DEFAULT NULL;
CREATE TABLE IF NOT EXISTS design_tags_master (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(50) NOT NULL, color VARCHAR(20) NOT NULL);
